require_relative '../lib/tabularDisplay.rb'
class Invoice
  attr_reader :products
  SalesTax = 10.0
  ImportDuty = 5.0
  def initialize
    @products = []
  end
  def add_product(product)
    @products << product
  end
  def generate_billable_amount
    grand_total = 0
    products.each do |product|
      product.price_incld_tax = cal_taxed_price(product)
      grand_total += product.price_incld_tax
    end
    grand_total.round(2)
  end
  def cal_sales_tax(product)
    sales_tax = 0.to_f
    sales_tax += (SalesTax / 100) * product.price    
    if product.is_exempted? 
      sales_tax = 0
    elsif product.is_imported?
      sales_tax += (ImportDuty / 100) * product.price
    end
    sales_tax.round(2)  
  end
  def cal_taxed_price(product)
    product.sales_tax = cal_sales_tax(product)
    product.price + product.sales_tax    
  end
  def show
    #Declaring headers, rows and footers as desired in the tabular display of bill
    headers = %w{ Name Price Imported? Exempted Sales_Tax Taxed_Price } 
    footers = ["Grand_Total", "=", generate_billable_amount]
    rows = []
    #Array of methods to be called on each product to derive values for each column of table 
    methods = [:name, :price, :import_status, :exemption, :sales_tax, :price_incld_tax]
    products.each do |product|
      row = []
      methods.each { |method| row << product.send(method) }
      rows << row
    end
    #An instance of TabularDisplay; a bill which is generated by generate bill function
    bill = TabularDisplay.new(headers, rows, footers)
    bill.generate_bill
  end
end